version: "3.3"

services:
  development:
    build:
      context: docker
      dockerfile: Dockerfile
    command: sshd
    container_name: nn_framework
    stdin_open: true
    tty: true
    ports:
      - "127.0.0.1:2223:22"

  debug:
    build:
      context: docker
      dockerfile: Dockerfile
    command: bash

  test:
    build:
      context: docker
      dockerfile: Dockerfile
    entrypoint: /test.sh

  run:
    build:
      context: docker
      dockerfile: Dockerfile
    entrypoint: /run.sh
